# Exclude some of GitLab files
AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable

Lint/DuplicateRegexpCharacterClassElement: # (new in 1.1)
  Enabled: true
Lint/EmptyBlock: # (new in 1.1)
  Enabled: true
Lint/NoReturnInBeginEndBlocks: # (new in 1.2)
  Enabled: true
Lint/ToEnumArguments: # (new in 1.1)
  Enabled: true
Lint/UnmodifiedReduceAccumulator: # (new in 1.1)
  Enabled: true
Style/ArgumentsForwarding: # (new in 1.1)
  Enabled: true
Style/CollectionCompact: # (new in 1.2)
  Enabled: true
Style/DocumentDynamicEvalDefinition: # (new in 1.1)
  Enabled: true
Style/NegatedIfElseCondition: # (new in 1.2)
  Enabled: true
Style/SwapValues: # (new in 1.1)
  Enabled: true

Layout/DotPosition:
  Enabled: false

Layout/LineLength:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/GlobalVars:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/SpecialGlobalVars:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
